<?php

namespace AppBundle\Repository;

/**
 * CityRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
