<?php

namespace AppBundle\Repository;

use AppBundle\Entity\FederalHotelPin;
use Doctrine\ORM\EntityRepository;

/**
 * FederalHotelPinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FederalHotelPinRepository extends EntityRepository
{
    /**
     * @return FederalHotelPin[]
     */
    public function getActivePins(): array
    {
        $qb = $this->createQueryBuilder('fhp');
        $qb->where('fhp.isActive = 1');

        return $qb->getQuery()->getResult();
    }
}
