<?php

namespace AppBundle\Repository;

/**
 * PinCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PinCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
